# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='text',
            field=models.TextField(null='false', unique=True, verbose_name='单词'),
        ),
    ]
