# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0002_auto_20160906_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='synonym',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dict',
            name='text',
            field=models.TextField(default='', unique=True, verbose_name='单词'),
        ),
    ]
