# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rwords', '0003_auto_20160906_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('name', models.TextField(default='unnamed wordbook')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dict',
            name='text',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.Dict'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='wordbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.WordBook'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='words',
            field=models.ManyToManyField(through='rwords.WordList', to='rwords.Dict'),
        ),
    ]
