# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 07:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('rwords', '0004_auto_20160906_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='authUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('amount', models.IntegerField(default=50)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LearnState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar_level', models.IntegerField(default=0, max_length=7)),
                ('to_simple', models.BooleanField(default=False)),
                ('learned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.authUser')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.WordList')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('shared', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.authUser')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.WordList')),
            ],
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.authUser'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='learning_wordbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.WordBook'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='notes',
            field=models.ManyToManyField(related_name='note_users', through='rwords.Note', to='rwords.WordList'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='states',
            field=models.ManyToManyField(related_name='learn_users', through='rwords.LearnState', to='rwords.WordList'),
        ),
    ]
