# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('rwords', '0006_auto_20160906_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='learning_wordbook',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='states',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user_ptr',
        ),
        migrations.RenameField(
            model_name='learnstate',
            old_name='to_simple',
            new_name='too_simple',
        ),
        migrations.AlterField(
            model_name='learnstate',
            name='familiar_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learnstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.UserProperty'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.UserProperty'),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='authUser',
        ),
        migrations.AddField(
            model_name='userproperty',
            name='learning_wordbook',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rwords.WordBook'),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='notes',
            field=models.ManyToManyField(related_name='note_users', through='rwords.Note', to='rwords.WordList'),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='states',
            field=models.ManyToManyField(related_name='learn_users', through='rwords.LearnState', to='rwords.WordList'),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='learnstate',
            unique_together=set([('user', 'word')]),
        ),
    ]
