# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0008_auto_20160906_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='text',
            new_name='text_chs',
        ),
        migrations.AddField(
            model_name='example',
            name='text_eng',
            field=models.TextField(default=''),
        ),
    ]
