# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0010_wordbook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='image',
            field=models.ImageField(default='', upload_to='bookfront/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='name',
            field=models.CharField(default='unnamed wordbook', max_length=150),
        ),
    ]
