# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0011_auto_20160907_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='image',
            field=models.ImageField(default='', upload_to='bookfront/%Y/%m/%d', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='name',
            field=models.CharField(default='unnamed wordbook', max_length=150, verbose_name='单词书名称'),
        ),
    ]
