# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0012_auto_20160907_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='单词书名称'),
        ),
    ]
