# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0013_auto_20160907_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='image',
            field=models.ImageField(upload_to='bookfront/%Y/%m/%d', verbose_name='封面图片'),
        ),
    ]
