# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0014_auto_20160907_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(auto_created=True, default=False)),
                ('build_date', models.DateField(auto_now_add=True)),
                ('userproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.UserProperty')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.WordList')),
            ],
        ),
        migrations.AddField(
            model_name='userproperty',
            name='tasks',
            field=models.ManyToManyField(related_name='learn_task_users', through='rwords.LearnTask', to='rwords.WordList'),
        ),
        migrations.AlterUniqueTogether(
            name='learntask',
            unique_together=set([('userproperty', 'word')]),
        ),
    ]
