# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0015_auto_20160907_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnstate',
            old_name='learned',
            new_name='master',
        ),
    ]
