# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0016_auto_20160907_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntask',
            name='first',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
