# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0017_learntask_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learntask',
            old_name='first',
            new_name='remember',
        ),
    ]
