# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0018_auto_20160907_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learntask',
            name='build_date',
            field=models.DateField(),
        ),
    ]
