# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0019_auto_20160908_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField(default='')),
                ('userproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwords.UserProperty')),
            ],
        ),
    ]
