# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0020_learndiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntask',
            name='unknown_flag',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
