# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0021_learntask_unknown_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learndiary',
            name='userproperty',
        ),
        migrations.DeleteModel(
            name='LearnDiary',
        ),
    ]
