# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwords', '0022_auto_20160908_0403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learntask',
            unique_together=set([('userproperty', 'word', 'build_date')]),
        ),
    ]
